(function(root){'use strict';
const crops={strawberry:{name:'Morango',icon:'🍓',time:600000,cost:4,sell:12,xp:8,level:1},corn:{name:'Milho',icon:'🌽',time:3600000,cost:12,sell:34,xp:18,level:2},sunflower:{name:'Girassol',icon:'🌻',time:14400000,cost:22,sell:65,xp:30,level:3},apple:{name:'Macieira',icon:'🍎',time:86400000,cost:45,sell:140,xp:60,level:4}};
const animals={chicken:{name:'Galinha',icon:'🐔',product:'egg',cost:65,time:600000,level:1},cow:{name:'Vaca',icon:'🐄',product:'milk',cost:220,time:1800000,level:3},sheep:{name:'Ovelha',icon:'🐑',product:'wool',cost:160,time:3600000,level:2}};
animals.pig={name:'Porquinho',icon:'🐷',product:'truffle',cost:190,time:2700000,level:3};
const products={truffle:{name:'Trufa',icon:'🍄',sell:52},egg:{name:'Ovo',icon:'🥚',sell:20},milk:{name:'Leite',icon:'🥛',sell:48},wool:{name:'Lã',icon:'🧶',sell:60}};
const decors={flower:{name:'Flores',icon:'🌷',cost:10},fence:{name:'Cerca',icon:'🪵',cost:8},bench:{name:'Banco',icon:'🪑',cost:25},tree:{name:'Árvore',icon:'🌳',cost:35},fountain:{name:'Fonte',icon:'⛲',cost:90},path:{name:'Caminho',icon:'🟫',cost:3},couple:{name:'Cantinho do casal',icon:'💞',cost:60}};
const upgrades={barn:{name:'Celeiro',icon:'🛖',cost:100,level:2,desc:'Colheitas vendem por 20% a mais.'},house:{name:'Nossa casa',icon:'🏡',cost:140,level:2,desc:'A visita diária rende mais 20 moedas.'},pond:{name:'Lago',icon:'💧',cost:180,level:3,desc:'Regar acelera 25%, em vez de 15%.'},mill:{name:'Moinho',icon:'🏭',cost:230,level:4,desc:'Produtos animais vendem por 25% a mais.'},greenhouse:{name:'Estufa',icon:'🪴',cost:320,level:5,desc:'Novas plantações crescem 20% mais rápido.'},garden:{name:'Jardim',icon:'🌼',cost:120,level:3,desc:'Mais quatro canteiros para cultivar.'},pasture:{name:'Área dos animais',icon:'🌾',cost:170,level:3,desc:'Espaço para até oito animais (antes, três).'}};
const day=t=>{const d=new Date(t);return [d.getFullYear(),d.getMonth()+1,d.getDate()].join('-')};
const weather=t=>((Math.floor(t/3600000)*7+13)%11<3?'rain':'sun');
const level=s=>1+Math.floor(s.xp/160);
const treeLevel=s=>1+Math.floor(s.love/80);
function fresh(now=Date.now()){return {v:1,coins:150,xp:0,love:0,plots:Array.from({length:12},(_,i)=>i<2?{crop:'strawberry',start:now-600000,ready:now-1,watered:false}:null),animals:[],bag:{},upgrades:[],decor:[],decoBag:{},gifts:[],notes:[],daily:{date:day(now),claimed:false,harvest:0,feed:0,flowers:0,rewards:[]},visits:[],pet:{xp:0,lastFeed:0,name:'Pipoca'},stats:{harvests:0,plantings:0},achievements:[],claimedTree:[],lastSaved:now}}
function sync(s,now){if(s.daily.date!==day(now))s.daily={date:day(now),claimed:false,harvest:0,feed:0,flowers:0,rewards:[]};return s}
function price(s,key){return Math.floor((crops[key]?.sell||products[key]?.sell||0)*(crops[key]&&s.upgrades.includes('barn')?1.2:products[key]&&s.upgrades.includes('mill')?1.25:1))}
function milestones(s){const checks=[['first','Primeira colheita',s.stats.harvests>=1],['hundred','100 plantações',s.stats.plantings>=100],['cow','Primeira vaca',s.animals.some(a=>a.type==='cow')],['ten','Fazenda nível 10',level(s)>=10]];let won=[];for(const [id,label,yes]of checks)if(yes&&!s.achievements.includes(id)){s.achievements.push(id);s.coins+=25;won.push(label)}return won}
function act(s,type,p={},now=Date.now()){sync(s,now);let msg='';const fail=m=>({ok:false,message:m});
if(type==='plant'){const c=crops[p.crop];if(!c||!Number.isInteger(p.index)||p.index<0||p.index>=s.plots.length)return fail('Esse canteiro não existe.');if(s.plots[p.index])return fail('Esse canteiro já está ocupado.');if(level(s)<c.level)return fail('Essa semente abre no nível '+c.level+'.');if(s.coins<c.cost)return fail('Faltam Love Coins para essa semente.');s.coins-=c.cost;const factor=(s.upgrades.includes('greenhouse')?.8:1)*(weather(now)==='rain'?.85:1);s.plots[p.index]={crop:p.crop,start:now,ready:now+c.time*factor,watered:false};s.stats.plantings++;if(p.crop==='sunflower')s.daily.flowers++;msg=c.name+' plantado. Pode fechar: o tempo continua passando.'}
else if(type==='water'){const plot=s.plots[p.index];if(!plot)return fail('Plante uma semente primeiro.');if(plot.ready<=now)return fail('Já está pronto para colher.');if(plot.watered)return fail('Esse canteiro já recebeu água.');plot.watered=true;plot.ready=now+(plot.ready-now)*(s.upgrades.includes('pond')?.75:.85);msg='Uma aguinha e um pouco de paciência. Crescimento acelerado.'}
else if(type==='harvest'){const plot=s.plots[p.index];if(!plot)return fail('Esse canteiro está vazio.');if(plot.ready>now)return fail('Ainda está crescendo.');s.bag[plot.crop]=(s.bag[plot.crop]||0)+1;s.xp+=crops[plot.crop].xp;s.love+=3;s.stats.harvests++;if(plot.crop==='strawberry')s.daily.harvest++;s.plots[p.index]=null;msg=crops[plot.crop].name+' na cesta! +'+crops[plot.crop].xp+' XP.'}
else if(type==='sell'){let total=0;for(const key of Object.keys(s.bag)){total+=price(s,key)*s.bag[key];s.bag[key]=0}if(!total)return fail('A cesta está vazia.');s.coins+=total;msg='Vendemos a colheita por '+total+' Love Coins.'}
else if(type==='animal'){const a=animals[p.kind];if(!a)return fail('Animal desconhecido.');if(level(s)<a.level)return fail('Esse animal chega no nível '+a.level+'.');if(s.animals.length>=(s.upgrades.includes('pasture')?8:3))return fail('Amplie a área dos animais para receber mais.');if(s.coins<a.cost)return fail('Ainda faltam moedas.');s.coins-=a.cost;s.animals.push({id:now+'-'+s.animals.length,type:p.kind,ready:0});msg=a.name+' chegou! Alimente para começar a produzir.'}
else if(type==='feed'){const a=s.animals.find(a=>a.id===p.id);if(!a)return fail('Animal não encontrado.');if(a.ready)return fail('Recolha a produção antes de alimentar de novo.');if(s.coins<3)return fail('A ração custa 3 moedas.');s.coins-=3;a.ready=now+animals[a.type].time;s.daily.feed++;s.love+=2;msg='Barriguinha cheia. Produção a caminho.'}
else if(type==='collect'){const a=s.animals.find(a=>a.id===p.id);if(!a||!a.ready)return fail('Alimente esse animal primeiro.');if(a.ready>now)return fail('A produção ainda não está pronta.');const key=animals[a.type].product;s.bag[key]=(s.bag[key]||0)+1;a.ready=0;s.xp+=12;s.love+=2;msg=products[key].name+' guardado na cesta. +12 XP.'}
else if(type==='daily'){if(s.daily.claimed)return fail('O carinho de hoje já está guardado.');s.daily.claimed=true;s.coins+=30+(s.upgrades.includes('house')?20:0);s.love+=10;if(!s.visits.includes(day(now)))s.visits.push(day(now));msg='Mais um dia juntinhos. Presente diário recebido!'}
else if(type==='quest'){const q={harvest:[10,60,30],feed:[3,45,25],flowers:[5,60,30]}[p.id];if(!q)return fail('Missão desconhecida.');if(s.daily.rewards.includes(p.id))return fail('Recompensa já recebida.');if(s.daily[p.id]<q[0])return fail('Ainda falta um pouquinho.');s.daily.rewards.push(p.id);s.coins+=q[1];s.xp+=q[2];s.love+=8;msg='Missão da dupla concluída! +'+q[1]+' moedas e '+q[2]+' XP.'}
else if(type==='upgrade'){const u=upgrades[p.id];if(!u)return fail('Melhoria desconhecida.');if(s.upgrades.includes(p.id))return fail('Essa melhoria já é de vocês.');if(level(s)<u.level)return fail('Libera no nível '+u.level+'.');if(s.coins<u.cost)return fail('Ainda faltam moedas para essa melhoria.');s.coins-=u.cost;s.upgrades.push(p.id);if(p.id==='garden')s.plots.push(null,null,null,null);s.love+=10;msg=u.name+' pronto. '+u.desc}
else if(type==='expand'){const stages=[{size:12,cost:80,level:2},{size:16,cost:150,level:4},{size:20,cost:250,level:6}];const st=stages.find(x=>s.plots.length<=x.size);if(!st||s.plots.length>=24)return fail('Vocês já abriram todo o terreno.');if(level(s)<st.level)return fail('Próxima área no nível '+st.level+'.');if(s.coins<st.cost)return fail('A expansão custa '+st.cost+' moedas.');s.coins-=st.cost;s.plots.push(null,null,null,null);msg='Quatro canteiros novos. Nosso mundo ficou maior.'}
else if(type==='decorBuy'){const d=decors[p.id];if(!d)return fail('Decoração desconhecida.');if(s.coins<d.cost)return fail('Ainda faltam moedas.');s.coins-=d.cost;s.decoBag[p.id]=(s.decoBag[p.id]||0)+1;msg=d.name+' na caixa de decoração. Escolha um lugar no terreno.'}
else if(type==='place'){if(!decors[p.id]||!s.decoBag[p.id])return fail('Compre esse item na lojinha.');if(!Number.isInteger(p.cell)||p.cell<0||p.cell>47)return fail('Escolha um espaço livre.');if(s.decor.some(d=>d.cell===p.cell))return fail('Já tem uma decoração aqui.');s.decoBag[p.id]--;s.decor.push({type:p.id,cell:p.cell});msg='Ficou a nossa cara.'}
else if(type==='remove'){const i=s.decor.findIndex(d=>d.cell===p.cell);if(i<0)return fail('Esse espaço está vazio.');const d=s.decor.splice(i,1)[0];s.decoBag[d.type]=(s.decoBag[d.type]||0)+1;msg='Guardado na caixa. Pode colocar em outro lugar.'}
else if(type==='pet'){if(now-s.pet.lastFeed<600000)return fail('Pipoca está satisfeito. Volte em alguns minutos.');if(s.coins<2)return fail('O petisco custa 2 moedas.');s.coins-=2;s.pet.lastFeed=now;s.pet.xp+=10;s.love+=3;msg='Pipoca abanou o rabinho. +10 XP de amizade.'}
else if(type==='gift'){if(!['Yudi','Karol'].includes(p.from))return fail('Escolha quem está jogando.');if(s.gifts.filter(g=>!g.opened).length>=20)return fail('Abram os presentes que estão na caixa primeiro.');if(s.coins<5)return fail('A flor de presente custa 5 moedas.');s.coins-=5;s.gifts.push({id:now+'-'+s.gifts.length,from:p.from,to:p.from==='Yudi'?'Karol':'Yudi',text:String(p.text||'Separei essa flor pra você.').slice(0,240),opened:false});msg='Presente deixado para '+(p.from==='Yudi'?'Karol':'Yudi')+'.'}
else if(type==='openGift'){const g=s.gifts.find(g=>g.id===p.id);if(!g||g.to!==p.user)return fail('Esse presente é para a outra pessoa.');if(g.opened)return fail('Já foi aberto.');g.opened=true;s.love+=8;msg=g.from+' deixou uma flor e um recadinho para você.'}
else if(type==='treeReward'){const n=Number(p.level);if(![2,3,5,8].includes(n)||treeLevel(s)<n)return fail('A árvore ainda está crescendo.');if(s.claimedTree.includes(n))return fail('Presente já recebido.');s.claimedTree.push(n);if(n===2){s.coins+=50;s.decoBag.flower=(s.decoBag.flower||0)+1}if(n===5){s.coins+=100;s.decoBag.couple=(s.decoBag.couple||0)+1}if(n===8){s.coins+=200;s.decoBag.fountain=(s.decoBag.fountain||0)+1}msg='Um presente entre os galhos. É de vocês.'}
else return fail('Ação desconhecida.');
const won=milestones(s);s.lastSaved=now;return {ok:true,message:msg+(won.length?' Conquista: '+won.join(', ')+'. +25 moedas por conquista.':'')};}
function valid(s){return !!s&&s.v===1&&Number.isFinite(s.coins)&&s.coins>=0&&Number.isFinite(s.xp)&&Number.isFinite(s.love)&&Array.isArray(s.plots)&&s.plots.length>=12&&s.plots.length<=28&&s.plots.every(p=>p===null||(crops[p.crop]&&Number.isFinite(p.ready)&&Number.isFinite(p.start)))&&Array.isArray(s.animals)&&s.animals.every(a=>animals[a.type]&&Number.isFinite(a.ready))&&s.daily&&typeof s.daily.date==='string'&&Array.isArray(s.daily.rewards)&&['upgrades','decor','gifts','visits','achievements','claimedTree'].every(k=>Array.isArray(s[k]))&&s.pet&&Number.isFinite(s.pet.xp)&&s.stats&&Number.isFinite(s.stats.harvests)&&s.bag&&s.decoBag}
const api={crops,animals,products,decors,upgrades,day,weather,level,treeLevel,fresh,sync,price,act,valid};if(typeof module!=='undefined')module.exports=api;root.Farm=api;
})(typeof globalThis!=='undefined'?globalThis:this);
