(function(root){'use strict';const normalize=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9,]/gi,'').toLowerCase();
function fresh(){return {v:2,active:null,actor:'Yudi',people:{Yudi:{xp:0,skills:{logic:2,perception:1,empathy:0},spent:0},Karol:{xp:0,skills:{logic:0,perception:1,empathy:2},spent:0}},cases:{}}}
const level=p=>1+Math.floor(p.xp/100);function campaign(c){return {seen:[],solved:[],links:[],hints:{},rolls:{},notes:'',done:false,attempts:0,focus:3,orders:{}}}
function unlocked(e,s){return !e.requires||s.solved.includes(e.requires)}
function act(state,cases,type,p={},random=Math.random){const c=cases.find(c=>c.id===(p.caseId||state.active)),s=c?state.cases[c.id]:null;const fail=message=>({ok:false,message});const award=n=>Object.values(state.people).forEach(x=>x.xp+=n);let message='';
if(type==='start'){if(!c)return fail('Caso não encontrado.');state.active=c.id;if(!state.cases[c.id])state.cases[c.id]=campaign(c);return {ok:true,message:'Pasta aberta. Comecem pela leitura da ocorrência.'}}
if(type==='actor'){if(!state.people[p.name])return fail('Escolha um dos investigadores.');state.actor=p.name;return {ok:true,message:p.name+' está conduzindo a investigação.'}}
if(type==='skill'){const person=state.people[p.name];if(!person||!(p.skill in person.skills))return fail('Habilidade desconhecida.');if(level(person)-1-person.spent<=0)return fail('Um novo nível dá um ponto de habilidade.');if(person.skills[p.skill]>=5)return fail('Essa habilidade já chegou a 5.');person.skills[p.skill]++;person.spent++;return {ok:true,message:'Habilidade aprimorada.'}}
if(!s||!c)return fail('Abra um caso primeiro.');
if(type==='inspect'){const e=c.evidence.find(e=>e.id===p.id);if(!e||!unlocked(e,s))return fail('Essa prova ainda não foi recuperada.');if(!s.seen.includes(e.id))s.seen.push(e.id);message='Prova adicionada ao caderno.'}
else if(type==='solve'){const puzzle=c.puzzles.find(x=>x.id===p.id);if(!puzzle)return fail('Enigma não encontrado.');if(s.solved.includes(p.id))return fail('Este enigma já foi resolvido.');if(!puzzle.needs.every(id=>s.seen.includes(id)))return fail('Examinem primeiro os documentos indicados.');if(normalize(p.answer)!==normalize(puzzle.answer))return fail('Isso ainda não combina com os documentos. Confiram os detalhes e tentem outra leitura.');s.solved.push(p.id);const xp=Math.max(10,20-(s.hints[p.id]||0)*5);award(xp);message=puzzle.explanation+' +'+xp+' XP para cada investigador.'}
else if(type==='roll'){const puzzle=c.puzzles.find(x=>x.id===p.id);if(!puzzle)return fail('Enigma desconhecido.');if(s.rolls[p.id])return fail('O dado desse desafio já foi lançado. O resultado fica guardado.');if(!puzzle.needs.every(id=>s.seen.includes(id)))return fail('Examinem os documentos antes de usar uma habilidade.');const die=Math.min(6,Math.floor(random()*6)+1),bonus=state.people[state.actor].skills[puzzle.skill],success=die+bonus>=5;s.rolls[p.id]={die,bonus,success,actor:state.actor};message=success?'Sucesso: a habilidade revelou uma pista sem gastar foco.':'O detalhe escapou. Vocês ainda podem resolver o enigma normalmente ou consultar uma pista.'}
else if(type==='hint'){const puzzle=c.puzzles.find(x=>x.id===p.id);if(!puzzle)return fail('Enigma desconhecido.');if(!puzzle.needs.every(id=>s.seen.includes(id)))return fail('Examinem os documentos primeiro.');const n=s.hints[p.id]||0;if(n>=puzzle.hints.length)return fail('Todas as pistas deste desafio já estão abertas.');s.hints[p.id]=n+1;s.focus=Math.max(0,s.focus-1);message=puzzle.hints[n]+' A recompensa deste enigma cai 5 XP; nunca fica abaixo de 10.'}
else if(type==='link'){if(!s.seen.includes(p.a)||!s.seen.includes(p.b)||p.a===p.b)return fail('Escolham duas provas diferentes já examinadas.');const d=c.deductions.find(d=>((d.a===p.a&&d.b===p.b)||(d.a===p.b&&d.b===p.a))&&d.relation===p.relation);if(!d)return fail('Essa ligação não fecha uma dedução necessária. Procurem uma contradição de álibi ou uma explicação do método ou motivo.');if(s.links.includes(d.id))return fail('Essa dedução já está no quadro.');s.links.push(d.id);message=d.text}
else if(type==='accuse'){if(s.done)return fail('O caso já está encerrado.');if(s.solved.length<c.puzzles.length||s.links.length<c.deductions.length)return fail('Resolvam os três enigmas e firmem as duas deduções antes de fechar o caso.');s.attempts++;if(p.suspect!==c.solution.suspect||p.motive!==c.solution.motive||p.proof!==c.solution.proof)return fail('O relatório tem uma lacuna. Confrontem o responsável, o motivo e a prova decisiva com os documentos. O caso continua aberto.');s.done=true;award(60);message='Caso encerrado. +60 XP para cada investigador.'}
else if(type==='notes'){s.notes=String(p.text||'').slice(0,6000);message='Anotações salvas.'}
else return fail('Ação desconhecida.');return {ok:true,message}}
function valid(s){return s&&s.v===2&&s.people&&['Yudi','Karol'].every(n=>s.people[n]&&Number.isFinite(s.people[n].xp)&&Number.isFinite(s.people[n].spent)&&['logic','perception','empathy'].every(k=>Number.isFinite(s.people[n].skills[k])))&&s.cases&&typeof s.cases==='object'&&Object.values(s.cases).every(c=>Array.isArray(c.seen)&&Array.isArray(c.solved)&&Array.isArray(c.links)&&c.hints&&c.rolls&&typeof c.notes==='string')}
const api={fresh,level,unlocked,act,valid,normalize};root.Detective=api;if(typeof module!=='undefined')module.exports=api;})(globalThis);
