(function(root){
const people={oriel:{name:'Oriel',cell:0},merchant:{name:'Mercador de poções',cell:1},marta:{name:'Dona Marta',cell:2},sarca:{name:'Vovó Sarça',cell:3},bento:{name:'Capitão Bento',cell:4},iracema:{name:'Dona Iracema',cell:5}};
const enemies={'Lobos do Véu':{cell:6},'Golem de Pedra':{cell:7,boss:true},'Criatura do Pântano':{cell:8},'Guardião do Pântano':{cell:9,boss:true},'Caranguejos do Véu':{cell:10},'Enguias do Véu':{cell:11},'Guardiã das Ondas':{image:'assets/rpg-water-guardian.png',boss:true}};
const npcNodes={oriel:['start','mensageiro','pergunta_porque','pergunta_perigo','pergunta_outros','partida','relíquia1','relíquia2'],merchant:['estrada_velha','merchant_yudi','merchant_karol','merchant_pergunta','merchant_caverna'],marta:['vila_ponte','dicas_marta','marta_guardiao','marta_historia','marta_dica','marta_lore','descanso_pergunta_pantano','descanso_suprimentos'],sarca:['bruxa_pantano','sarca_veu','sarca_historia','sarca_ajuda','sarca_troca'],bento:['chegada_farois','capitao_bento','bento_veu','bento_reliquia','bento_naufragio','bento_oriel','escolha_rota_mar','rota_barco','retorno_vila','retorno_pergunta_vila'],iracema:['dona_iracema','iracema_veu','iracema_historia','iracema_farol','iracema_ajuda','entrada_farol']};
const golemNodes=['caverna_furtivo','caverna_barulho','sala_golem','golem_repete','golem_esgueirar','resposta_certa','resposta_errada'];
const waterNodes=['camara_naufragio','guardia_ondas','ondas_repete','ondas_forcar','onda_certa','onda_errada'];
function forNode(id,node){if(node.combat)return{name:node.combat.enemyName,...enemies[node.combat.enemyName],hostile:true};if(golemNodes.includes(id))return{name:'Golem de Pedra',...enemies['Golem de Pedra']};if(waterNodes.includes(id))return{name:'Guardiã das Ondas',...enemies['Guardiã das Ondas']};for(const [key,ids]of Object.entries(npcNodes))if(ids.includes(id))return people[key];return null}
const api={people,enemies,npcNodes,forNode};if(typeof module!=='undefined')module.exports=api;else root.RPGCast=api;
})(globalThis);
