/* Caso 05: documentos e soluções autorais; campanha anterior preservada. */
CASES.push({id:'teatro-v1',number:'05',title:'O aplauso que ninguém ouviu',place:'Teatro das Andorinhas',date:'Sexta-feira · ensaio geral',tag:'AVANÇADO · 8 enigmas · 4 deduções',color:'#b295cf',summary:'O cenário caiu sobre um palco vazio. O ensaio havia terminado. Então por que o sistema registrou uma plateia aplaudindo?',intro:'Às 22h20, a ponte cenográfica desceu sem comando da mesa. Ninguém se feriu: o elenco já havia saído. Dentro do mecanismo, a polícia encontrou um calço retirado e um temporizador. O teatro fecharia no dia seguinte se uma vistoria apontasse risco estrutural. Quatro pessoas permaneceram no prédio. Vocês precisam separar o acidente fabricado das pequenas mentiras que não têm relação com ele.',brief:'Descubram quem programou a queda, qual documento pretendia impedir e como usou o som do ensaio como álibi. Há oito enigmas encadeados e quatro ligações necessárias.',suspects:[
{id:'ines',name:'Inês Vidal',initials:'IV',role:'Diretora',quote:'Fiquei na plateia até o último aplauso.',bio:'Ameaçara cancelar a montagem, mas tinha investido as próprias economias nela.',answers:[['O último aplauso?','Ouvi ao passar pelo corredor. Não olhei para o relógio.'],['Depois disso?','Fui à bilheteria conferir os ingressos com o contador.'],['A vistoria?','Eu queria que tudo fosse examinado antes de abrir.']]},
{id:'raul',name:'Raul Neri',initials:'RN',role:'Técnico de som',quote:'Som gravado não prova que havia alguém na sala.',bio:'Criou as trilhas e discutiu com a produção sobre pagamentos.',answers:[['Quem usa a cabine?','Todos têm acesso ao tocador de testes. A mesa principal fica comigo.'],['Seu posto?','Fiquei com a recepcionista entre 22h e 22h20.'],['A gravação?','O arquivo de aplausos inclui uma tosse. É fácil reconhecer.']]},
{id:'celso',name:'Celso Amaral',initials:'CA',role:'Administrador',quote:'Eu estava no arquivo, lendo o relatório em voz alta.',bio:'Assinou a compra dos novos componentes e controlava o orçamento.',answers:[['Alguém viu?','A portaria ouviu minha voz pelo interfone.'],['Chaves?','A minha era a do armário vermelho. A escala está no livro.'],['Relatório?','A vistoria podia esperar. A casa precisava de uma estreia.']]},
{id:'lia',name:'Lia Costa',initials:'LC',role:'Cenógrafa',quote:'O calço não cai sozinho. Alguém soltou a trava.',bio:'Construiu a ponte e pediu uma avaliação dos materiais recebidos.',answers:[['Onde estava?','Na oficina, em chamada de vídeo com a fornecedora.'],['O material?','As peças instaladas não pareciam as da nota fiscal.'],['O temporizador?','Era de testes de luz. O manual ficou na gaveta.']]}
],evidence:[
{id:'sync',title:'Dois relógios',kind:'CALIBRAÇÃO',body:'O registrador avança 65 minutos a cada 60 minutos oficiais. Às 21h00 oficiais, marcava 21h00. A abertura do painel aparece às 22h18 no registrador. O desvio cresce de forma constante.'},
{id:'keys',title:'Chaves do turno',kind:'ESCALA',body:'Cada pessoa recebeu uma única chave: azul, branca, verde ou vermelha. Raul recebeu azul. Lia não recebeu branca nem vermelha. Inês não recebeu vermelha. A ordem da fechadura é AZUL, BRANCA, VERDE, VERMELHA.'},
{id:'cue',title:'Deixa anotada',kind:'CADERNO DE PALCO',body:'O bilhete diz: “Leia somente o primeiro caractere de cada linha, de cima para baixo.”\nCortina presa.\nAjustar o foco.\nBancos fora.\nInspecionar cabos.\nNada no centro.\nEncerrar.'},
{id:'manual',title:'Manual do tocador',kind:'ENVELOPE RECUPERADO',requires:'acrostic',body:'CABINE: cada letra foi avançada pela sequência repetida 1, 2, 3 no alfabeto ABCDEFGHIJKLMNOPQRSTUVWXYZ. Ao ultrapassar Z, voltar ao A. O trecho cifrado é BTTVKYP. A palavra indica onde buscar a gravação usada no ensaio.'},
{id:'audio',title:'Gravação do arquivo',kind:'ANÁLISE DE ÁUDIO',requires:'cipher',body:'A voz de Celso entre 22h08 e 22h16 repete a mesma frase, a mesma respiração e o mesmo clique a cada 24 segundos. No final de cada ciclo há exatamente a tosse do arquivo de aplausos de Raul. O interfone aceitava entrada de áudio por cabo; não havia imagem.'},
{id:'routes',title:'Passagens técnicas',kind:'PLANTA DE SERVIÇO',body:'Percursos bidirecionais, tempos em minutos: A–B 2; B–D 4; A–C 3; C–D 1; D–E 1; B–E 8. A é o arquivo; D é o painel; E é o armário de ferramentas. É obrigatório passar por D. Nenhum outro corredor está aberto. A passagem C só abre às 22h09. A saída de A foi às 22h08. Esperar junto à porta é permitido.'},
{id:'timer',title:'Temporizador',kind:'MANUAL TÉCNICO',body:'O temporizador dispara após exatamente 7 minutos completos. Ele foi armado às 22h13 oficiais. O registrador marca a ABERTURA do painel, não o instante de armar. Primeiro se abre; depois se arma e fecha. Todos os demais relógios desta pasta usam hora oficial.'},
{id:'weights',title:'Três peças',kind:'BALANÇA',body:'As caixas A, B e C têm 1 kg de embalagem cada. Pesagens brutas em pares: A+B=13 kg; A+C=16 kg; B+C=19 kg. O calço original tem 4 kg líquidos. Qual caixa pode contê-lo? Não confundam peso bruto com líquido.'},
{id:'recovered',title:'O calço recuperado',kind:'PERÍCIA',requires:'weight',body:'Na caixa A foi encontrado o calço de 4 kg. Seu número T-41 coincide com o inventário da ponte. Há resíduo fresco do selante do painel na luva guardada junto dele. A luva tem a etiqueta de Celso e sua impressão digital na face interna; a sequência de câmera contínua do corredor mostra Celso levando a caixa A até o armário E às 22h14.'},
{id:'alibis',title:'Imagens contínuas',kind:'REGISTROS EXTERNOS',body:'22h05–22h19: Inês é vista com o contador na bilheteria. 22h00–22h20: Raul é visto na recepção. 22h04–22h17: Lia aparece na chamada de vídeo na oficina, com relógio oficial ao fundo. Celso é apenas ouvido pelo interfone. Das salas filmadas até D seriam necessários pelo menos cinco minutos; as imagens não apresentam cortes.'},
{id:'invoice',title:'Notas da compra',kind:'CONTABILIDADE',body:'A nota assinada por Celso cobra 12 suportes certificados a 180 reais cada. A fornecedora confirma a entrega de 12 suportes comuns a 75 reais cada. O extrato registra o total cobrado e um repasse de apenas 900 reais à fornecedora. A vistoria do dia seguinte compararia números de série e pagamentos.'},
{id:'report',title:'A vistoria cancelada',kind:'CORRESPONDÊNCIA',requires:'money',body:'Mensagem de Celso, preservada no servidor às 21h40: “Se interditarem por acidente, a perícia da compra fica para depois. Preciso tirar o relatório da pauta de amanhã.” O relatório de Lia identificava a diferença entre suportes comuns e certificados e a responsabilidade de quem autorizou a compra.'},
{id:'schedule',title:'Folha de reconstrução',kind:'REGISTRO CRUZADO',requires:'route',body:'Câmera oficial: Celso sai do arquivo às 22h08, atravessa C às 22h11, deixa D às 22h13 e chega a E às 22h14. A porta A–C leva três minutos de caminhada e, por isso, já estava aberta quando ele chegou. A voz continuou sendo ouvida até 22h16.'}
],puzzles:[
{id:'clock',title:'Um relógio que acelera',type:'code',skill:'perception',needs:['sync'],prompt:'A que hora OFICIAL o painel foi aberto? Responda HH:MM.',answer:'2212',placeholder:'HH:MM',hints:['Do ponto de calibração até a abertura, o registrador avança 78 minutos.','65 minutos de registro equivalem a 60 reais. Converta 78 antes de somar a 21h00.'],explanation:'78 × 60/65 = 72 minutos: abertura às 22h12.'},
{id:'keys',title:'As cores não dizem os nomes',type:'code',skill:'logic',needs:['keys'],prompt:'Quem recebeu as chaves azul, branca, verde e vermelha? Escrevam os quatro primeiros nomes separados por vírgulas.',answer:'Raul,Ines,Lia,Celso',placeholder:'Nome,Nome,Nome,Nome',hints:['Fixem Raul. Lia só tem uma cor disponível.','Depois de reservar azul e verde, Inês não pode ficar com vermelha.'],explanation:'Raul: azul; Lia: verde; Inês: branca; Celso: vermelha.'},
{id:'acrostic',title:'A margem do ensaio',type:'code',skill:'perception',needs:['cue'],prompt:'Qual local as linhas indicam?',answer:'CABINE',placeholder:'Local',hints:['A instrução do bilhete é literal.','Juntem C, A e as quatro iniciais seguintes.'],explanation:'As iniciais formam CABINE, onde está o manual do tocador.'},
{id:'cipher',title:'Três passos, recomeçar',type:'code',skill:'logic',needs:['manual'],prompt:'Decifrem BTTVKYP seguindo o manual. Qual local aparece?',answer:'ARQUIVO',placeholder:'Local',hints:['Para desfazer um avanço, recuem. A chave recomeça na quarta letra.','B−1=A; T−2=R; T−3=Q. Continuem com 1, 2, 3, 1.'],explanation:'Os recuos 1,2,3,1,2,3,1 transformam BTTVKYP em ARQUIVO.'},
{id:'route',title:'O caminho com uma porta atrasada',type:'code',skill:'logic',needs:['routes'],prompt:'Qual percurso de A até E, passando por D, permite a chegada mais cedo, desconsiderando o tempo de trabalho no painel? Escrevam as letras sem separadores.',answer:'ACDE',placeholder:'Percurso',hints:['Incluam a espera somente se chegarem à porta antes de abrir.','A chegada em C seria às 22h11. Comparem os dois caminhos até D.'],explanation:'A–C–D–E leva 3+1+1=5 minutos; sem parada, chega às 22h13. A–B–D–E leva 7. Não é preciso esperar em C.'},
{id:'weight',title:'O peso que falta na ficha',type:'code',skill:'logic',needs:['weights'],prompt:'Qual caixa contém massa líquida compatível com o calço? A, B ou C.',answer:'A',placeholder:'Caixa',hints:['Somem os três pares e dividam por dois.','As caixas juntas pesam 24 kg. Retirem B+C para achar A e descontem sua embalagem.'],explanation:'A=5 kg brutos, B=8 e C=11. A contém 4 kg líquidos.'},
{id:'money',title:'Uma diferença assinada',type:'code',skill:'logic',needs:['invoice'],prompt:'Qual valor, em reais inteiros, foi cobrado além do material efetivamente entregue?',answer:'1260',placeholder:'Valor sem símbolo',hints:['O preço unitário excedente se repete nas doze peças.','Calculem 12 × (180−75).'],explanation:'2160 reais cobrados menos 900 repassados: diferença de 1260 reais.'},
{id:'timeline',title:'A voz ficou depois da pessoa',type:'order',skill:'empathy',needs:['sync','timer','schedule','audio','recovered'],prompt:'Ordenem os fatos. A abertura do painel, o acionamento e a queda são momentos diferentes.',items:[{id:'fall',text:'A ponte cai'},{id:'voice',text:'A repetição de voz termina'},{id:'arm',text:'Temporizador é armado'},{id:'exit',text:'Celso sai do arquivo'},{id:'box',text:'A caixa chega ao armário E'},{id:'open',text:'O painel é aberto'}],answer:'exit,open,arm,box,voice,fall',hints:['Corrijam primeiro 22h18 do registrador. Depois somem sete minutos ao acionamento.','Saída 22h08; abertura 22h12; acionamento 22h13; caixa 22h14; fim do áudio 22h16; queda 22h20.'],explanation:'Celso já estava longe quando a ponte caiu. O temporizador explica o intervalo; a gravação explica a voz sem presença.'}
],deductions:[{id:'voice',a:'audio',b:'alibis',relation:'contradiz',text:'O áudio repetido contradiz o uso da voz como prova de presença de Celso.'},{id:'delay',a:'timer',b:'schedule',relation:'explica',text:'O disparo programado explica como o autor deixou o painel antes da queda.'},{id:'motive',a:'invoice',b:'report',relation:'explica',text:'A diferença na compra explica o interesse em adiar a vistoria.'},{id:'author',a:'recovered',b:'schedule',relation:'explica',text:'O calço identificado, a luva e a filmagem vinculam Celso ao transporte e ao mecanismo.'}],solution:{suspect:'celso',motive:'Adiar a vistoria que revelaria o desvio na compra',motives:['Adiar a vistoria que revelaria o desvio na compra','Vingar a redução do cachê de Raul','Impedir que Inês vendesse o teatro','Proteger a ponte de uma sobrecarga'],proof:'recovered',ending:'Celso instalou um áudio repetido para simular presença, retirou o calço e armou a queda para sete minutos depois. A câmera do corredor, o calço T-41 e a luva ligam o método a ele; a contabilidade explica o motivo. Inês confundiu uma gravação com o fim do ensaio, mas isso não a torna autora da sabotagem. Lia entrega o relatório, a estrutura é reparada e a primeira sessão segura começa com um aplauso que desta vez é de verdade.'}});
