/* Casos autorais. Cada id é permanente para preservar campanhas já salvas.
   Novos casos podem ser acrescentados ao array sem alterar o motor. */
globalThis.CASES=[
{id:'relogio-v1',number:'01',title:'O relógio que parou',place:'Oficina Vasconcelos · Rua das Acácias, 18',date:'Quinta-feira, 23 de abril',tag:'Cronologia · documentos · álibis',color:'#b9915b',summary:'Um relojoeiro morto. Um relógio parado. E quatorze minutos que não pertencem àquela noite.',intro:'Às 21h52, a aprendiz encontrou Renato Vasconcelos caído ao lado da bancada. O relógio de pulso marcava 21h37. Na rua, a chuva tinha apagado quase tudo. Dentro da oficina, alguém havia limpado o busto de bronze — e esquecido de olhar para a câmera do outro lado da calçada. Renato pretendia entregar uma denúncia na manhã seguinte. Vocês receberam a chave da oficina e os registros recolhidos naquela noite.',brief:'Descubram quem matou Renato, por que a denúncia era perigosa e qual registro derruba o álibi.',suspects:[
{id:'bianca',name:'Bianca Menezes',role:'Irmã e responsável pelas vendas',initials:'BM',quote:'Eu estava no trem das nove e dez. A gente discutiu, sim. Família discute.',bio:'Fazia a contabilidade e negociava as peças restauradas. Renato havia retirado seu acesso ao inventário naquela semana.',answers:[['Sobre a discussão','Ele me acusou de não entender o valor das peças. Depois de dez anos pagando as contas daquele lugar.'],['Sobre a passagem','Comprei na estação. Nove e dez está impresso no papel. Vocês podem conferir.'],['Sobre o busto','Pesado demais para ficar na beirada da bancada. Eu sempre disse isso.']]},
{id:'alvaro',name:'Álvaro Barros',role:'Aprendiz de restauração',initials:'AB',quote:'Saí para buscar o jantar. Quando voltei, a porta estava encostada.',bio:'Trabalhava com Renato havia oito meses. Foi quem chamou o socorro às 21h52.',answers:[['Onde estava?','Na lanchonete do outro quarteirão. O pedido atrasou. Podem olhar a câmera de lá.'],['Renato estava preocupado?','Separou três ordens de serviço e guardou um caderno no cofre. Disse que a peça mais antiga abria a memória.'],['Quem tinha chave?','Eu, ele e Bianca. A chave dela tinha um cordão vermelho.']]},
{id:'caio',name:'Caio Queiroz',role:'Colecionador',initials:'CQ',quote:'O relógio era meu. Eu queria uma explicação, não uma tragédia.',bio:'Ameaçou processar a oficina após descobrir uma peça substituída em uma restauração.',answers:[['Quando foi embora?','Às 20h50. Fui direto ao hospital visitar minha mãe.'],['O que Renato contou?','Que estava levantando as vendas dos últimos meses. Ia me ligar pela manhã.'],['Conhece Bianca?','Foi ela quem me vendeu a restauração. Renato só trabalhava nas peças.']]},
{id:'diana',name:'Diana Tavares',role:'Jornalista',initials:'DT',quote:'Ele marcou uma conversa comigo às oito da manhã. Não apareceu.',bio:'Investigava a circulação de antiguidades adulteradas.',answers:[['Que denúncia era?','Ele não quis dizer por telefone. Pediu que eu levasse um gravador e cópias de notas fiscais.'],['Saiu de casa?','Eu estava apresentando uma transmissão ao vivo das 21h às 22h.'],['Ele citou alguém?','Disse apenas: “É pior quando a assinatura é de casa.”']]}
],evidence:[
{id:'clock',title:'Relógio de pulso',kind:'EXAME DA PEÇA',place:'Bancada',body:'Ponteiros em 21h37. A coroa está puxada. Não há dano nas engrenagens. O relógio foi parado manualmente; esse horário não estabelece o momento da morte.'},
{id:'orders',title:'Ordens de serviço',kind:'ARQUIVO · 3 FICHAS',place:'Gaveta',body:'Bilhete de Renato: “A peça mais antiga abre a memória. Use os quatro números da ordem de serviço.”',table:[['Peça','Ano','OS'],['Carrilhão','1928','9037'],['Relógio de bolso','1874','6821'],['Cronômetro naval','1902','4519']]},
{id:'camera',title:'Câmera da farmácia',kind:'CAPTURA DE VÍDEO',place:'Rua',body:'Tela: 21:32. Uma mulher com o casaco e o broche de Bianca abre a oficina. Conferência técnica: o relógio dessa câmera estava ADIANTADO em 14 minutos. A gravação é contínua e cobre todas as entradas até 21h30.'},
{id:'ticket',title:'Passagem amassada',kind:'VIA DO PASSAGEIRO',place:'Depoimento de Bianca',body:'Origem: Vila Serena. Destino: Santa Lúcia. Passageira: Bianca Menezes.',table:[['Operação','Horário'],['Compra no terminal','21:10'],['Partida do trem','22:10'],['Embarque validado','22:04']]},
{id:'audio',title:'Gravador da bancada',kind:'TRANSCRIÇÃO · HORÁRIO VERIFICADO',place:'Bancada',body:'21:22 — Renato: “Bianca, devolve esse caderno.”\n21:22:08 — Bianca: “Você não vai entregar isso.”\n21:22:11 — Impacto, queda de objetos.\n21:26 — Porta de serviço fecha.\nO socorro confirmou que o ferimento fatal é compatível com o busto de bronze encontrado na bancada.'},
{id:'alibis',title:'Conferência dos álibis',kind:'REGISTRO EXTERNO',place:'Central',body:'Álvaro: câmera contínua da lanchonete entre 21h06 e 21h45. Caio: portaria e câmera do hospital entre 21h03 e 22h10. Diana: transmissão ao vivo com participação do público entre 21h e 22h. Nenhum dos três aparece entrando na oficina nesse intervalo.'},
{id:'ledger',title:'O caderno de Renato',kind:'PROVA RECUPERADA · COFRE',requires:'safe',body:'“Bianca vendeu as peças originais, registrou réplicas como restaurações e reteve a diferença. Anexei comprovantes assinados e os números das contas. Amanhã levo tudo à jornalista.” Há uma venda assinada por Bianca no dia anterior.'},
{id:'return',title:'Retorno às 21h18',kind:'CRONOLOGIA CORRIGIDA',requires:'time',body:'A imagem das 21h32 corresponde a 21h18 reais. Bianca voltou à oficina doze minutos depois de dizer que já estava em um trem. A passagem registra apenas uma COMPRA às 21h10.'},
{id:'sequence',title:'Os oito minutos',kind:'RECONSTITUIÇÃO',requires:'sequence',body:'21h18: Bianca entra. 21h22: discussão e impacto. 21h26: ela sai com um objeto embrulhado, retorna por segundos e sai sem ele. Não há outra entrada. O relógio parado às 21h37 é uma encenação posterior ao impacto.'}
],puzzles:[
{id:'safe',title:'O cofre das peças antigas',skill:'logic',type:'code',needs:['orders'],prompt:'Qual código de quatro dígitos abre o cofre? As ordens de serviço e o bilhete de Renato estão no arquivo.',answer:'6821',placeholder:'4 dígitos',hints:['A peça mais antiga é a de menor ano, não a primeira da lista.','O relógio de bolso é de 1874. O código vem da ordem de serviço dessa peça.'],explanation:'1874 é o menor ano. A OS correspondente é 6821. O caderno estava atrás da prateleira inferior.'},
{id:'time',title:'Quatorze minutos fora do lugar',skill:'perception',type:'code',needs:['camera','ticket'],prompt:'A câmera mostra 21:32, mas está adiantada em 14 minutos. A que horas Bianca realmente entrou? Responda HH:MM.',answer:'2118',placeholder:'HH:MM',hints:['Um relógio adiantado mostra um horário mais tarde do que o real.','Subtraia 14 minutos de 21:32.'],explanation:'21:32 − 14 minutos = 21:18. A passagem não é um álibi: 21:10 era a hora da compra.'},
{id:'sequence',title:'Reconstruam a noite',skill:'logic',type:'order',needs:['audio','return'],prompt:'Organizem os acontecimentos do primeiro ao último. Usem as setas; o horário do pulso não é uma fonte confiável.',items:[{id:'exit',text:'A porta de serviço fecha'},{id:'entry',text:'Bianca entra, na câmera corrigida'},{id:'impact',text:'O gravador registra discussão e impacto'}],answer:'entry,impact,exit',hints:['A câmera corrigida marca 21h18; o gravador tem horário verificado.','Entrada 21h18, impacto 21h22, saída 21h26.'],explanation:'A sequência coloca Bianca dentro da oficina no momento do impacto e elimina a falsa referência das 21h37.'}
],deductions:[{id:'alibi',a:'ticket',b:'return',relation:'contradiz',text:'A hora de compra da passagem não prova que Bianca estava viajando.'},{id:'motive',a:'ledger',b:'audio',relation:'explica',text:'A denúncia das vendas explica a tentativa de tomar o caderno e a discussão.'}],solution:{suspect:'bianca',motive:'Impedir a denúncia das vendas fraudulentas',motives:['Receber a herança imediatamente','Impedir a denúncia das vendas fraudulentas','Recuperar um relógio que pertencia a Caio'],proof:'sequence',ending:'Bianca usou a hora de compra da passagem como álibi e parou o relógio de pulso para empurrar a cronologia para mais tarde. Mas o vídeo corrigido, o gravador e a ausência de outras entradas fecham os oito minutos. O caderno explica o motivo. Vocês não resolveram o caso por um palpite sobre a personalidade dela: reconstruíram o que aconteceu.'}},
{id:'vidro-v1',number:'02',title:'O cofre de vidro',place:'Cine Aurora · sala de montagem',date:'Sábado, 16 de maio',tag:'Cifra · código Morse · documentos',color:'#779799',summary:'Na véspera da estreia, o único corte final de um filme desaparece de um armário lacrado. O lacre continua inteiro.',intro:'Luiza Prado passou dois anos filmando o bairro antes da demolição. Na manhã da estreia, o SSD do corte final sumiu. A porta de vidro estava lacrada e a câmera do corredor não registrou ninguém abrindo o armário. No computador, restaram um arquivo com senha, cinco grupos de sinais e uma cópia de inventário com valores errados. A estreia é às oito. Luiza só pediu uma coisa: tragam o filme de volta.',brief:'Descubram quem retirou o SSD, como atravessou o armário lacrado e onde escondeu o filme.',suspects:[
{id:'tadeu',name:'Tadeu Bittencourt',role:'Editor do filme',initials:'TB',quote:'Eu deixei o SSD exatamente onde ela mandou. Não sou responsável pelo armário.',bio:'Sua participação nos créditos foi reduzida após uma discussão. Conhece o fluxo de cópias e o mobiliário da sala.',answers:[['Sobre os créditos','Meu nome aparece por três segundos. Depois de noites aqui dentro.'],['Sobre o armário','Esse móvel era do teatro. Deve ter uns vinte anos. Qualquer marceneiro desmonta.'],['Sobre o áudio','Faço exercícios de Morse desde criança. Mas isso não quer dizer nada.']]},
{id:'valeria',name:'Valéria Aguiar',role:'Produtora',initials:'VA',quote:'Se esse filme não estrear, perdemos dinheiro. Muito.',bio:'Guardava a chave da porta de vidro. A chave nunca saiu de seu chaveiro.',answers:[['Quem lacrou?','Eu e Luiza, juntas. Assinamos por cima da fita.'],['Havia cópia?','O backup remoto estava subindo. Tadeu disse que precisava de mais um dia.'],['Onde passou a noite?','No hotel com os convidados. Há registro da recepção e do jantar.']]},
{id:'zoe',name:'Zoe Furtado',role:'Técnica de projeção',initials:'ZF',quote:'Eu só preciso do arquivo até as seis. Depois disso, não prometo milagre.',bio:'Foi vista entrando no cinema com uma mala de ferramentas.',answers:[['O que consertou?','O projetor. Minha ordem de serviço está carimbada na cabine, no outro andar.'],['Você conhecia o móvel?','Não. Na sala de montagem só fui hoje de manhã.'],['Quem ficou por último?','Ouvi o Tadeu descer a escada. Ele estava cantarolando.']]},
{id:'augusto',name:'Augusto Meireles',role:'Zelador',initials:'AM',quote:'Fechei o portão às dez. Dentro, cada setor cuida do que é seu.',bio:'Tem a chave da entrada e acesso à oficina de manutenção.',answers:[['Ferramentas saíram?','Uma chave Phillips. Está no livro de retirada.'],['O fundo do armário?','É aparafusado. O lacre só protege a frente.'],['Foi à montagem?','Não naquela noite. Fiquei na portaria, de frente para a câmera.']]}
],evidence:[
{id:'seal',title:'Lacre assinado',kind:'INSPEÇÃO · ARMÁRIO',place:'Sala de montagem',body:'A fita na porta está inteira, com as assinaturas de Luiza e Valéria. Atrás do móvel, quatro parafusos têm marcas recentes. A placa traseira pode sair sem tocar na porta de vidro.'},
{id:'cipher',title:'Senha do arquivo de notas',kind:'POST-IT DO EDITOR',place:'Computador',body:'“Minha cidade, três casas à frente: VHUUD.”\nNa mesma folha: ABCDEFGHIJKLMNOPQRSTUVWXYZ.\nA anotação explica que, ao escrever a senha, cada letra original foi avançada três posições no alfabeto.'},
{id:'morse',title:'Cinco grupos no áudio',kind:'TRANSCRIÇÃO DOS SINAIS',place:'Computador',body:'Os pulsos curtos e longos foram transcritos sem ruído. Cada grupo é uma letra:\n.-..   ..   ...-   .-.   ---\nTabela disponível: A .- / I .. / L .-.. / O --- / R .-. / S ... / V ...- / E . / T -'},
{id:'inventory',title:'Inventário do armário',kind:'FOLHA DE PATRIMÔNIO',place:'Armário',body:'Só uma peça pesa menos do que deveria. O SSD retirado pesa 48 g. As caixas foram pesadas sem embalagem externa.',table:[['Peça','Peso registrado','Peso encontrado'],['Estojo azul','320 g','320 g'],['Estojo verde','286 g','238 g'],['Estojo preto','410 g','410 g']]},
{id:'tools',title:'Livro de ferramentas',kind:'REGISTRO ASSINADO',place:'Portaria',body:'21h04 — Retirada de chave Phillips: Tadeu Bittencourt.\n21h41 — Devolução: Tadeu Bittencourt.\n21h50 — Augusto confere o inventário.\nA câmera da escada registra Tadeu levando a ferramenta à montagem e voltando com um livro.'},
{id:'backup',title:'Estado das cópias',kind:'LOG DO SISTEMA',place:'Computador',body:'O upload remoto foi cancelado manualmente às 21h12 na conta de Tadeu. Valéria estava no hotel; Zoe estava na cabine com o projetor ligado e Augusto na portaria. O filme não foi apagado, apenas removido do estojo.'},
{id:'notes',title:'Rascunho de e-mail',kind:'ARQUIVO DESBLOQUEADO',requires:'caesar',body:'De Tadeu para Luiza, não enviado: “Sem meu nome como coautor, não tem estreia. Você vai precisar me ouvir. O vidro não é a única entrada.”'},
{id:'book',title:'O livro de capa oca',kind:'OBJETO RECUPERADO',requires:'morse',body:'No livro de Tadeu, sobre sua mesa, há uma cavidade com o SSD. O número de série confere com o registro do corte final. Um marcador traz a mesma escrita do post-it.'},
{id:'green',title:'O estojo verde',kind:'CONFERÊNCIA DE PESO',requires:'weight',body:'286 − 238 = 48 g. O estojo verde é o único com a falta exata de um SSD. No fundo removível do armário há uma marca de poeira alinhada com esse estojo.'}
],puzzles:[
{id:'caesar',title:'Três casas para voltar',skill:'logic',type:'code',needs:['cipher'],prompt:'Recuperem a senha original escondida em VHUUD. Cada letra da senha foi avançada três posições.',answer:'SERRA',placeholder:'A senha original',hints:['Para desfazer uma cifra que avançou, volte no alfabeto.','V volta para S; H volta para E. Aplique o mesmo às outras letras.'],explanation:'V→S, H→E, U→R, U→R, D→A. A senha é SERRA.'},
{id:'morse',title:'O que os pulsos dizem?',skill:'perception',type:'code',needs:['morse'],prompt:'Usem a tabela da transcrição para transformar os cinco grupos de sinais em uma palavra. Esse é o esconderijo.',answer:'LIVRO',placeholder:'Uma palavra',hints:['Espaços largos separam as letras. O primeiro grupo é .-..','Os dois primeiros grupos são L e I. O último é O.'],explanation:'.-.. = L, .. = I, ...- = V, .-. = R, --- = O. A pista leva ao livro na mesa do editor.'},
{id:'weight',title:'Quarenta e oito gramas',skill:'logic',type:'choice',needs:['inventory'],prompt:'Qual estojo perdeu exatamente o peso do SSD? Comparem o peso registrado com o encontrado.',options:['Estojo azul','Estojo verde','Estojo preto'],answer:'Estojo verde',hints:['Calculem a diferença de cada linha, não comparem apenas os pesos finais.','286 menos 238 é igual a 48.'],explanation:'O verde perdeu 48 g, exatamente o peso do SSD. Isso identifica a posição usada para alcançar o objeto pela traseira.'}
],deductions:[{id:'method',a:'seal',b:'tools',relation:'explica',text:'A ferramenta retirada pelo editor permite remover o fundo sem romper o lacre.'},{id:'leverage',a:'notes',b:'backup',relation:'explica',text:'Cancelar o backup torna o SSD uma forma de pressionar Luiza sobre os créditos.'}],solution:{suspect:'tadeu',motive:'Pressionar Luiza para mudar os créditos',motives:['Vender o filme para outro cinema','Pressionar Luiza para mudar os créditos','Evitar o superaquecimento do projetor'],proof:'book',ending:'Tadeu cancelou a cópia remota, retirou o fundo aparafusado e alcançou o estojo verde. O lacre na frente nunca foi uma barreira para esse caminho. O rascunho explica a pressão; o SSD no livro, com número de série confirmado, encerra a busca. Luiza estreia o filme. Dessa vez, vocês ficam para ver os créditos.'}},
{id:'estufa-v1',number:'03',title:'A última flor da estufa',place:'Jardim Botânico de Vila Serena',date:'Domingo, 7 de junho',tag:'Mapa · proporções · lógica',color:'#909b69',summary:'Uma muda rara some na noite da exposição. Alguém deixou água demais e uma etiqueta a menos.',intro:'A botânica Elisa cultivou durante sete anos uma variedade de camélia que só agora floresceu. Na noite anterior à exposição, o vaso desapareceu da estufa central. Não há vidro quebrado. O chão do corredor leste está molhado, uma etiqueta de transporte foi rasgada e o controle de irrigação foi alterado. Elisa insiste: a planta não suporta o frio do lado de fora. Se ainda estiver no jardim, vocês precisam encontrá-la antes do amanhecer.',brief:'Encontrem o vaso e provem quem o retirou. Um interesse suspeito, sozinho, não basta.',suspects:[
{id:'iris',name:'Íris Nogueira',role:'Curadora da exposição',initials:'IN',quote:'Eu devia estar decidindo a iluminação, não explicando por que peguei um carrinho.',bio:'Negociava com um colecionador particular. Tinha autorização para mover vasos, mas não para retirá-los da exposição.',answers:[['Por que pegou o carrinho?','Para os painéis. São pesados. Deixei tudo no depósito.'],['Qual caminho usou?','O corredor oeste. O leste estava molhado e eu não quis sujar o sapato.'],['Sobre o colecionador','Ele patrocina eventos. Receber uma mensagem não é aceitar uma proposta.']]},
{id:'bento',name:'Bento Luz',role:'Jardineiro',initials:'BL',quote:'Aquela flor não tem preço para Elisa. Eu sei quanto trabalho deu.',bio:'Cuidava da irrigação e conhecia o painel. Seu crachá estava guardado na oficina durante a noite.',answers:[['Quem mexe no painel?','Qualquer crachá de funcionário abre. O sistema registra qual foi usado.'],['As botas molhadas?','Reguei o viveiro às oito. Isso está na escala.'],['O vaso pode estar fora?','Com esse frio? Quem conhece a planta a deixaria na sala aquecida.']]},
{id:'marina',name:'Marina Reis',role:'Fotógrafa',initials:'MR',quote:'Fotografei a flor às nove. Ela ainda estava lá.',bio:'A última imagem da planta em exposição está em sua câmera.',answers:[['Tem o arquivo original?','Sim, com horário conferido e sequência completa.'],['Viu alguém?','Íris com o carrinho vazio às 21h08. Na volta, tinha uma lona por cima.'],['Saiu por onde?','Pela recepção. Deixei meu crachá de visitante com o segurança.']]},
{id:'raul',name:'Raul Campos',role:'Segurança',initials:'RC',quote:'Nenhum veículo saiu. Se levaram, levaram a pé — ou ainda está aqui.',bio:'A portaria tem registro contínuo. Sua ronda não passa pelo interior da sala aquecida.',answers:[['Houve saída?','Depois de 21h, só Marina. Ela passou pela revista sem bolsa grande.'],['A porta da sala aquecida?','Fecha sozinha. Crachás permanentes conseguem abri-la.'],['Quem ficou?','Bento na oficina, Elisa no laboratório e Íris montando a exposição.']]}
],evidence:[
{id:'map',title:'Mapa dos compartimentos',kind:'PLANTA DO JARDIM',place:'Portaria',body:'Colunas de oeste para leste: 1, 2, 3. Linhas de norte para sul: A, B, C. Bilhete no carrinho: “Manter aquecido. Compartimento mais a leste, na linha central.”',table:[['','1 · oeste','2','3 · leste'],['A · norte','Recepção','Oficina','Estufa fria'],['B · centro','Depósito','Estufa central','Sala aquecida'],['C · sul','Pátio','Laboratório','Viveiro']]},
{id:'irrigation',title:'Controle de irrigação',kind:'REGISTRO DO PAINEL',place:'Estufa central',body:'Vazão do corredor leste: 6 litros por minuto. Volume liberado: 42 litros. Início: 21h10. O piso permaneceu molhado até a limpeza às 22h. O comando foi feito com o crachá IN-04, atribuído a Íris.'},
{id:'soles',title:'Marcas no corredor',kind:'REGISTRO DE PISO',place:'Corredor leste',body:'Há marcas de duas rodas estreitas e solas com desenho de losangos indo da estufa central à sala aquecida. Os sapatos de Íris têm losangos e ainda estavam molhados na vistoria; as botas de Bento têm linhas horizontais.'},
{id:'schedule',title:'Escala e observações',kind:'TRÊS REGISTROS',place:'Portaria',body:'Entre 21h e 21h30, cada pessoa usou um equipamento diferente: câmera, mangueira ou carrinho. Marina aparece com a câmera na filmagem. Bento não usou o carrinho e não aparece com a câmera. Íris é a terceira pessoa. Ninguém trocou de equipamento nesse intervalo.'},
{id:'offer',title:'Conversa com o colecionador',kind:'MENSAGEM APRESENTADA POR ÍRIS',place:'Depoimento',body:'20h42 — Colecionador: “Pago o combinado se você separar a camélia antes da abertura.”\n20h44 — Íris: “Deixo em um lugar protegido. Venha depois que o portão abrir.”\nA curadora diz que se referia a uma réplica, mas não há réplica no inventário.'},
{id:'inventory',title:'Inventário de exposição',kind:'CONFERÊNCIA',place:'Estufa',body:'Uma camélia rara, vaso de barro com selo EL-07. Nenhuma réplica. Às 21h, Marina fotografou o vaso no pedestal. Às 21h24, a câmera da recepção mostra Íris retornando com um carrinho coberto. Os painéis já estavam montados desde as 19h.'},
{id:'plant',title:'A camélia em B3',kind:'VASO RECUPERADO',requires:'mapcode',body:'A planta estava na sala aquecida, sob uma lona. O selo EL-07 confirma o vaso da exposição. Preso à alça do carrinho está um recibo de transporte preenchido e assinado por Íris.'},
{id:'window',title:'Sete minutos de água',kind:'CÁLCULO CONFERIDO',requires:'watermath',body:'42 litros ÷ 6 litros por minuto = 7 minutos. A irrigação foi de 21h10 a 21h17. As rodas e as solas passaram pelo piso molhado após esse intervalo; a afirmação de Íris de que não usou o leste não combina com as marcas.'},
{id:'cart',title:'O carrinho de Íris',kind:'ELIMINAÇÃO LÓGICA',requires:'equipment',body:'Marina usou a câmera. Bento, que não usou câmera nem carrinho, ficou com a mangueira. O carrinho só pode ter sido usado por Íris. A versão dos painéis é contradita pelo inventário e pelas imagens das 19h.'}
],puzzles:[
{id:'mapcode',title:'Onde a flor esperou?',skill:'perception',type:'grid',needs:['map'],prompt:'Toquem no compartimento indicado pelo bilhete: o mais a leste, na linha central.',options:['A1','A2','A3','B1','B2','B3','C1','C2','C3'],answer:'B3',hints:['Leste é a coluna 3. A linha central é B.','O encontro da linha B com a coluna 3 é a sala aquecida.'],explanation:'B3: a sala aquecida. O selo EL-07 confirma que a muda encontrada é a que desapareceu.'},
{id:'watermath',title:'Quanto tempo choveu por dentro?',skill:'logic',type:'code',needs:['irrigation'],prompt:'A válvula libera 6 litros por minuto e soltou 42 litros. Por quantos minutos ficou aberta? Digitem apenas o número.',answer:'7',placeholder:'Minutos',hints:['Volume é vazão multiplicada pelo tempo. Para achar o tempo, divida.','42 ÷ 6 = 7.'],explanation:'Foram sete minutos: de 21h10 a 21h17. Depois disso, o corredor continuou molhado.'},
{id:'equipment',title:'Três pessoas, três ferramentas',skill:'empathy',type:'choice',needs:['schedule','inventory'],prompt:'Pelos registros da escala, quem usou o carrinho entre 21h e 21h30?',options:['Marina Reis','Bento Luz','Íris Nogueira'],answer:'Íris Nogueira',hints:['Marina já tem a câmera. Bento não usou nem câmera nem carrinho.','Só resta a mangueira para Bento. O carrinho fica com a terceira pessoa.'],explanation:'Cada equipamento tinha uma pessoa. Eliminadas a câmera de Marina e a mangueira de Bento, resta Íris com o carrinho.'}
],deductions:[{id:'route',a:'soles',b:'window',relation:'contradiz',text:'Os sapatos molhados com losangos contradizem o relato de Íris sobre usar apenas o oeste.'},{id:'sale',a:'offer',b:'plant',relation:'explica',text:'A negociação e o recibo assinado explicam por que a camélia foi separada para retirada.'}],solution:{suspect:'iris',motive:'Separar a camélia para uma venda particular',motives:['Salvar a planta de uma doença','Separar a camélia para uma venda particular','Levar os painéis para outra exposição'],proof:'plant',ending:'Íris acionou a irrigação, levou a camélia pelo corredor leste e a escondeu na sala aquecida para entregá-la ao colecionador depois da abertura. O recibo assinado e o selo do vaso fecham a identificação; as marcas e a cronologia contradizem o caminho que ela alegou usar. Elisa recebe a planta a tempo. Na manhã seguinte, a primeira flor abre para todo mundo.'}}
];
