/* Caso perito, independente dos anteriores. Não altera IDs ou progressos já salvos. */
(()=>{
const doc=(id,title,body,requires)=>({id,title,body,kind:requires?'ENVELOPE RECUPERADO':'DOCUMENTO DE CAMPO',...(requires?{requires}:{place:'Pasta da estação'})});
const code=(id,title,skill,needs,prompt,answer,hints,explanation,placeholder='Resposta')=>({id,title,skill,type:'code',needs,prompt,answer,hints,explanation,placeholder});
CASES.push({id:'mare-morta-v1',number:'06',title:'O arquivo da maré morta',place:'Estação Hidrográfica de Várzea Alta · ilha do Meio',date:'Domingo · noite de fechamento da comporta',tag:'PERITO · 12 enigmas · 6 deduções',color:'#84a9c0',summary:'O laudo original desapareceu de uma estação isolada. Um substituto tem todas as assinaturas. Para separar os dois, vocês terão de remontar a operação por três caminhos diferentes.',intro:'Às 22h19, um aviso de vazamento esvaziou o arquivo da estação. O envelope M-27 continuava na gaveta. Só na manhã seguinte perceberam que as páginas descreviam uma amostra diferente. O barco da auditoria chega ao amanhecer. Quatro pessoas tinham acesso, e ninguém saiu da ilha.\n\nA pasta foi dividida em três frentes: expedição, manutenção e autoria. Algumas respostas abrem documentos de outra frente. Este caso foi preparado para ser resolvido com anotações: uma pista isolada nunca fecha a acusação.',brief:'Recuperem o laudo original, descubram quando ele foi transportado, identifiquem quem fez a troca e provem a finalidade da falsificação. Há 12 enigmas e 6 deduções. Todas as convenções estão nos documentos. Os enigmas numéricos têm solução única nas condições dadas; espaços e acentos não importam. O código de grupos numéricos deve ser copiado sem separadores.',suspects:[
{id:'maia',name:'Maia Lemos',initials:'ML',role:'Restauradora de documentos',quote:'O envelope parecia antigo. Isso não diz a idade das páginas.',bio:'Recuperou documentos danificados pela umidade e contestou a conservação do arquivo.',answers:[['O selo prova autenticidade?','Não. O lacre protege o envelope; a folha interna tem o próprio número de amostra.'],['Onde estava?','No posto de análise de selantes. A câmera mostra meu rosto, não só o crachá.'],['Quem conhecia as cifras?','Os quatro. Fazem parte da rotina de transporte da estação.']]},
{id:'nilo',name:'Nilo Reis',initials:'NR',role:'Engenheiro de manutenção',quote:'A comporta automática não foi aberta por alguém apertando um botão.',bio:'Escreveu os manuais de passagem e tinha acesso às ferramentas.',answers:[['Sobre os pulsos','A coincidência dos três pulsos abre a comporta por um minuto. O sistema é mecânico.'],['Sobre a ferramenta','Meu alicate tem a mandíbula numerada. Os empréstimos passam pela mesa filmada.'],['Sobre a rota','O painel de exposição mede unidades fictícias de umidade para proteger os documentos. O filtro do posto E troca o invólucro, zerando a leitura.']]},
{id:'olga',name:'Olga Brandão',initials:'OB',role:'Coordenadora do contrato',quote:'Uma amostra ruim não invalida uma obra inteira.',bio:'Autorizou o relatório de aceitação e negociou a liberação da última parcela da obra.',answers:[['Onde estava?','Entrei no arquivo para conferir uma numeração. Depois usei as passagens técnicas. Isso faz parte do meu trabalho.'],['Sobre o aviso','Ouvi pelo alto-falante, como todo mundo.'],['Sobre o contrato','Se a última parcela não sair, haverá uma investigação de cada assinatura. Inclusive a minha.']]},
{id:'teo',name:'Teo Azevedo',initials:'TA',role:'Arquivista',quote:'A letra no protocolo parece a minha. Não fui eu que escrevi.',bio:'Organizou os volumes e havia pedido transferência da estação.',answers:[['Sobre os armários','As etiquetas indicam lotes, não nomes de pessoas. Não atribuam um pacote a alguém só por uma letra.'],['Sobre as folhas','Nossos formulários de circulação têm cópias em branco. Não são assinaturas digitais.'],['Onde estava?','Na conferência de bombas, com registro contínuo. Podem conferir quem foi escalado para cada posto.']]}
],evidence:[
doc('dispatch','Cinco cargas, uma ordem','Frente de expedição. As cargas A, B, C, D e E ocuparam os cinco lugares de uma fila, cada uma exatamente uma vez. A não ocupou uma extremidade. Entre D e E havia exatamente uma carga; D veio antes de E. B era vizinha de E e veio antes dela. C veio antes de A; A veio antes de B.\n\nPara produzir a chave, troquem A por 1, B por 2, C por 3, D por 4 e E por 5, mantendo a ordem da fila.'),
doc('telegram','A tira de 22 algarismos','Texto recebido: 2142414142124315143234\n\nO remetente escreveu o texto original, de 22 algarismos, em linhas de CINCO posições, da esquerda para a direita. A última linha ficou incompleta, sem preenchimento. Numerou as colunas usando a chave das cinco cargas, da esquerda para a direita. Depois leu cada coluna de cima para baixo, na ordem de seus cabeçalhos 1, 2, 3, 4, 5.\n\nA tarefa é desfazer essa leitura por colunas. Nem todas têm o mesmo comprimento.'),
doc('columnkey','Chave de expedição conferida','A fila conferida fornece os cabeçalhos 3, 1, 4, 2, 5. Eles pertencem às posições físicas das colunas, não à ordem em que se deve escrever o texto. Usem esta chave com a tira de 22 algarismos.','queue'),
doc('square','O quadrado sem J','Depois de remontar a tira, separem em pares. Em cada par, o PRIMEIRO número indica a linha, o SEGUNDO indica a coluna. Linhas e colunas começam em 1.\n\n        1  2  3  4  5\nlinha 1: A  B  C  D  E\nlinha 2: F  G  H  I  K\nlinha 3: L  M  N  O  P\nlinha 4: Q  R  S  T  U\nlinha 5: V  W  X  Y  Z\n\nNão é necessário acrescentar letras ou interpretar uma metáfora.'),
doc('pairs','A tira remontada','Resultado preservado pelo terminal: 2211311542241134244434. O documento do quadrado explica como converter os pares em letras.','columns'),
doc('plan','Planta da galeria encontrada','A indicação é GALERIA OITO, identificada pela letra H na planta. Origem do transporte: A. O percurso precisa passar por E para recolher o invólucro de conservação. Não se pode repetir uma sala.\n\nCada passagem tem dois valores: MINUTOS / EXPOSIÇÃO À UMIDADE. São vias de mão dupla e não existem outras.\nA–B 2/3; A–C 4/1; B–C 1/2; B–D 2/4; C–E 3/3; C–F 4/1; D–G 2/1; E–F 1/1; E–G 2/4; F–G 2/2; G–H 2/2; A–E 10/4; E–H 8/4.\n\nA exposição começa em zero e não pode exceder 5 em nenhum ponto. Somem a exposição da passagem ANTES de verificar a chegada. Só depois de chegar a E com um valor válido, a troca instantânea do invólucro zera a exposição. Não há esperas obrigatórias. Busquem o caminho válido de menor duração, não o que tem menos portas.','location'),
doc('route','Percurso de conservação','O percurso válido mais rápido é A–C–E–F–G–H. O transporte saiu de A às 22h05 oficiais, sem paradas extras. O filtro em E opera instantaneamente. Usem os tempos da planta para reconstruir as passagens. A abertura da comporta H depende dos três pulsos do manual de manutenção.','path'),
doc('pulses','Três pulsos de manutenção','Frente de manutenção. Contem t em minutos inteiros a partir das 20h00 oficiais. A operação ocorreu entre t=0 e t=180, inclusive. A comporta H só abre quando os três circuitos pulsam ao mesmo tempo.\nCircuito azul: t deixa resto 4 ao dividir por 7.\nCircuito cobre: t deixa resto 5 ao dividir por 11.\nCircuito branco: t deixa resto 7 ao dividir por 13.\n\nResto significa o que sobra depois de retirar grupos completos. Exemplo: 18 dividido por 7 deixa resto 4. Não usem esse exemplo como um horário do caso.'),
doc('gate','A única janela da comporta','Os circuitos coincidiram às 22h17 oficiais. O sensor registrou a passagem de um invólucro nessa janela. O alerta no arquivo foi emitido dois minutos depois. O aviso não era condição para abrir H.','pulse'),
doc('radio','Três palavras corrompidas','Três grupos recebidos, na ordem: 1100010 / 0001010 / 0011000. Cada grupo tem SETE bits e exatamente UM bit invertido.\n\nNumerem os bits de 1 a 7, da esquerda para a direita. Três testes devem ter uma quantidade PAR de bits 1:\nP1 testa posições 1,3,5,7.\nP2 testa posições 2,3,6,7.\nP4 testa posições 4,5,6,7.\n\nSe um teste tiver quantidade ímpar, ele falhou. Somem os números dos testes que falharam (1, 2 e/ou 4): a soma indica a posição do bit que deve ser invertido. Corrijam esse bit. Depois leiam APENAS as posições 3,5,6,7, nessa ordem. Seus pesos são 8,4,2,1. Somem os pesos das posições que contêm 1. Cada grupo produz um algarismo. Concatenem os três.'),
doc('cabinet','O compartimento 629','O código corrigido abre o compartimento de índices 629. Dentro há quatro gavetas, W, X, Y e Z. Exatamente UMA contém o manifesto original. Exatamente DUAS das quatro frases abaixo são verdadeiras, avaliadas sobre a localização real do manifesto. As outras duas são falsas.\nW: “O manifesto está em X ou em Y.”\nX: “O manifesto não está em W.”\nY: “O manifesto está em Z.”\nZ: “O manifesto não está em X.”\n\nNão há uma regra especial para a frase da gaveta ocupada.','bits'),
doc('manifest','Manifesto original da gaveta','O manifesto da gaveta X lista os lotes: S4827-3, S4829-3, S5827-3 e S4927-3. Um único código passou corretamente pelo verificador; os outros foram copiados com erros.\n\nUma folha de rastreio acompanhava o lote correto: amostra de drenagem nº 27, coleta a montante, selante fluorescente da família Q. O selo do envelope, sozinho, não permite escolher qual amostra está nas páginas.','drawer'),
doc('checksum','Regra de controle dos lotes','Um código tem a forma S abcd-k, com quatro algarismos abcd e um controle k. Calculem 2a + 3b + 5c + 7d. Dividam por 11 e tomem o RESTO, que deve coincidir com k. Não usem soma simples nem o quociente. Todos os candidatos do manifesto usam controle 3. Respondam só os quatro algarismos do lote que passa.'),
doc('original','O laudo do lote verificado','S4827-3 é o único código válido. As páginas recuperadas nesse lote descrevem a AMOSTRA 27, retirada a montante, onde a obra deveria impedir infiltração. Resultado: REPROVADO. A análise microscópica confirma as fibras do papel original e o selante Q.\n\nAs páginas deixadas na gaveta do arquivo descrevem AMOSTRA 72, retirada num reservatório limpo fora da obra. Resultado: APROVADO. Ambas as análises laboratoriais são verdadeiras. A fraude está em apresentar a segunda como se fosse da primeira.','lot'),
doc('mix','Três frascos sem rótulo','Frente de autoria. X, Y e Z são concentrações percentuais de três frascos de selante fictício; todos os volumes são aditivos.\nMisturar 2 partes de X com 1 parte de Y produz concentração 40/3 por cento.\nMisturar 1 parte de Y com 1 parte de Z produz 30 por cento.\nMisturar 1 parte de X com 1 parte de Z produz 25 por cento.\n\nO resíduo do envelope retirado corresponde ao frasco Y. Descubram sua concentração, em porcentagem, sem arredondar as equações intermediárias. Não precisam manipular produtos: tudo é resolvido no papel.'),
doc('residue','O resíduo e as mandíbulas','O frasco Y contém 20%. Esse é o selante Q do laudo original. Na aba retirada, ele foi pressionado por uma ferramenta com DOIS entalhes assimétricos, nas posições 2 e 5.\nFerramentas examinadas: L1 tem entalhes 1 e 5; L2 tem 2 e 4; L3 tem apenas 5; L4 tem 2 e 5. O selante ainda estava fresco quando recebeu a marca. A aba do envelope substituto não tem essa marca.','mixture'),
doc('roster','Quatro pessoas, quatro postos','Cada suspeito ocupou um único posto na janela 22h00–22h10: selantes, bombas, rádio ou arquivo. Cada posto recebeu uma pessoa.\nMaia não estava no rádio nem no arquivo.\nNilo não estava em selantes nem no arquivo.\nTeo não estava no rádio.\nOlga estava no arquivo OU em bombas.\nO registro confirma que Teo já estava no seu posto quando a pessoa do rádio chegou. O posto do arquivo só foi ocupado a partir de 22h01.\nO vídeo da troca de turno mostra que a pessoa em selantes era Maia.\nO rádio foi ocupado por quem retirou L2.'),
doc('loans','Cadeia de custódia das ferramentas','A mesa de empréstimos tem câmera contínua com os rostos visíveis. Maia retirou L1; Nilo retirou L2; Olga retirou L4; Teo retirou L3. Cada pessoa ficou com sua ferramenta até devolvê-la às 22h25. Não houve troca: a única passagem entre os setores atravessa essa mesa filmada, e a estação foi revistada; não havia ferramentas equivalentes.\n\nRegistros de presença com imagem contínua: posto de selantes 21h58–22h20; posto de bombas 21h59–22h22; posto de rádio 22h00–22h21. No arquivo, o registro identifica a pessoa abrindo a gaveta às 22h03; a imagem da ferramenta fica parcialmente oculta pela própria mão. Depois das 22h05, essa pessoa sai pelo corredor A.'),
doc('identity','Identidade confrontada','A escala e a retirada de ferramentas colocam Maia em selantes, Nilo no rádio, Teo em bombas e Olga no arquivo. As câmeras dos três primeiros postos não apresentam cortes. A filmagem da gaveta identifica Olga, mas ela tinha autorização para manusear papéis; isso, por si só, não prova uma troca. Comparem a ferramenta sob sua custódia com a marca no selante do laudo que foi recuperado.','operator'),
doc('contract','O que liberava o pagamento','O contrato liberava a última parcela apenas com a aprovação da AMOSTRA 27, colhida a montante. A coordenadora responsável pelo aceite era Olga. Seu termo autorizava o pagamento como se a amostra 27 tivesse sido aprovada. O financeiro suspendeu a transferência ao saber da auditoria.\n\nA análise da amostra 72 havia sido solicitada legitimamente por Nilo para calibrar equipamentos e nunca foi apresentada por ele como teste da obra.'),
doc('alarm','Não havia água no sensor','O sensor permaneceu seco durante toda a noite. Às 21h56, foi agendado um alerta de teste para o minuto exato em que seria publicado. O registro de configuração mostra que o aviso era sintético, mas a senha de manutenção era compartilhada pelos quatro suspeitos. A senha não identifica o autor.\n\nA gaveta foi aberta às 22h03 oficiais. O envelope retirado chegou a A às 22h05. Todos os horários desta pasta são oficiais; não há relógios a corrigir neste caso.'),
doc('sequence','Reconstituição auditável','21h56: teste de alarme agendado. 22h03: gaveta aberta. 22h05: saída de A. 22h09: chegada a C. 22h12: troca de invólucro em E. 22h13: chegada a F. 22h15: chegada a G. 22h17: passagem por H. 22h19: alerta de teste publicado.\n\nO laudo já estava fora do arquivo antes do aviso. O movimento em H coincide com a única abertura possível da comporta e com a rota que preserva o papel.','timeline')
],puzzles:[
code('queue','01 · A fila que vira uma chave','logic',['dispatch'],'Reconstruam a fila de cinco cargas. Convertam as letras em algarismos segundo a regra do documento. Qual é a chave?','31425',['Usem cinco posições. Tratem “entre” como distância de duas posições e “vizinha” como distância de uma.','B está imediatamente antes de E. Experimentem as posições possíveis de D e E antes de encaixar A e C.'],'A única fila compatível é C, A, D, B, E. A conversão fornece 31425.','Cinco algarismos'),
code('columns','02 · As colunas incompletas','logic',['telegram','columnkey'],'Desfaçam a transposição. Respondam com os 22 algarismos do texto ANTES da leitura por colunas, sem espaços.','2211311542241134244434',['Dividam 22 por 5: quatro linhas completas e duas posições na última. As duas primeiras colunas físicas têm um elemento extra.','As colunas de cabeçalhos 1 e 3 têm cinco algarismos. As de cabeçalhos 2, 4 e 5 têm quatro. Separem o recebido nessa ordem numérica antes de restaurar a ordem física.'],'Blocos recebidos: 21424 | 1414 | 21243 | 1514 | 3234. Na ordem física 3,1,4,2,5, as linhas são 22113 / 11542 / 24113 / 42444 / 34.','22 algarismos'),
code('location','03 · Uma segunda leitura','perception',['pairs','square'],'Usem os pares da tira remontada no quadrado. Qual indicação completa de localização foi escondida?','GALERIAOITO',['Não leiam os algarismos isoladamente. Cada dois selecionam uma única casa.','Há onze pares. O quadrado não usa J, e a posição de I não muda.'],'22 11 31 15 42 24 11 34 24 44 34 forma GALERIA OITO.','Indicação completa'),
code('path','04 · Chegar rápido não basta','logic',['plan'],'Encontrem a rota válida de MENOR duração de A até H, passando por E e respeitando a exposição em todos os trechos. Respondam todas as letras do percurso, incluindo A e H.','ACEFGH',['Eliminem um caminho assim que a exposição ultrapassar 5; não esperem chegar ao filtro para verificar.','A–B–C parece rápido, mas chega à passagem C–E com exposição demais. Depois de E, o atalho direto a G também precisa ser verificado até H.'],'A–C–E chega a E em 7 minutos com exposição 4. O filtro zera a leitura. E–F–G–H leva 5 minutos e acumula 5. Total: 12 minutos. Os atalhos mais rápidos excedem o limite.','Letras do percurso'),
code('pulse','05 · A coincidência dos três ciclos','logic',['pulses'],'Em qual horário oficial a comporta abriu? Procurem a única coincidência dentro da janela do manual. Resposta HH:MM.','2217',['Listem primeiro os minutos do circuito de período 11, depois filtrem pelos outros restos. Não somem os períodos.','Os candidatos do segundo circuito começam em 5,16,27… e vão até 180. Testem os restos de cada sobrevivente.'],'O único t entre 0 e 180 com restos 4,5,7 é 137. Somando 137 minutos a 20h00: 22h17.','HH:MM'),
code('bits','06 · O erro faz parte da mensagem','perception',['radio'],'Corrijam um bit em cada grupo e convertam os quatro bits úteis. Qual código de três algarismos foi enviado?','629',['Façam três testes de paridade para CADA grupo. O valor de um teste é 1, 2 ou 4, não a quantidade de bits nele.','Invertam só a posição indicada pela soma dos testes que falharam. Só depois leiam as posições 3,5,6,7 com pesos 8,4,2,1.'],'Os erros estavam nas posições 5,2,7. Corrigidos: 1100110 / 0101010 / 0011001. Os dados são 0110, 0010, 1001: 6,2,9.','Três algarismos'),
code('drawer','07 · Duas verdades, quatro gavetas','logic',['cabinet'],'Em qual gaveta está o manifesto? Testem todas as localizações possíveis contra a regra de exatamente duas frases verdadeiras.','X',['Suponham uma localização e avaliem as quatro frases como verdadeiras ou falsas. Depois mudem a hipótese.','A frase na gaveta ocupada não tem privilégio: pode ser verdadeira ou falsa. Contem os resultados de cada hipótese.'],'Se estiver em W, há 1 frase verdadeira; em X, 2; em Y, 3; em Z, 3. Apenas X satisfaz a condição.','W, X, Y ou Z'),
code('lot','08 · O original entre cópias válidas demais','perception',['manifest','checksum'],'Qual lote passa pelo controle matemático? Respondam somente seus quatro algarismos.','4827',['O controle é o resto da soma PONDERADA. A posição do algarismo muda seu peso.','Para cada candidato, multipliquem os algarismos por 2,3,5,7 e retirem múltiplos completos de 11 da soma.'],'As somas são 91,105,93,94; os restos são 3,6,5,6. Apenas 4827 coincide com o controle declarado 3.','Quatro algarismos'),
code('mixture','09 · O frasco intermediário','logic',['mix'],'Qual é a concentração do frasco Y? Respondam o número percentual sem o símbolo %.','20',['Uma mistura 2:1 contém três partes. Multipliquem sua concentração por três antes de montar a primeira equação.','As equações são 2X+Y=40, Y+Z=60 e X+Z=50. Subtraiam as duas últimas e substituam na primeira.'],'Y−X=10. Substituindo Y=X+10 em 2X+Y=40, resulta X=10, Y=20, Z=40.','Porcentagem inteira'),
code('operator','10 · Cargo, posto e instrumento','empathy',['roster','loans','residue'],'Quem estava no arquivo e tinha sob custódia a única ferramenta compatível com a marca no selante? Primeiro nome. Não concluam o motivo só por isso.','Olga',['Montem duas correspondências separadas: pessoa–posto e pessoa–ferramenta. Só depois cruzem a marca.','Maia fixa selantes e a retirada de L2 fixa o rádio. O rádio foi ocupado às 22h00; Teo já estava no seu posto. Comparem isso com a primeira ocupação do arquivo.'],'Maia ocupa selantes. Nilo retirou L2 e ocupa rádio. Teo já estava no posto antes das 22h00 e, portanto, não poderia ocupar o arquivo, que abriu às 22h01: fica em bombas. Olga ocupa o arquivo. L4, sob custódia de Olga, coincide com os dois entalhes.','Primeiro nome'),
{id:'timeline',title:'11 · O aviso veio depois',type:'order',skill:'logic',needs:['route','plan','gate','alarm'],prompt:'Ordenem estes oito acontecimentos. Calculem as passagens pela planta e usem a coincidência dos ciclos; não tratem o alarme como o início da operação.',items:[{id:'alarm',text:'Alerta de teste publicado'},{id:'filter',text:'Invólucro trocado em E'},{id:'gate',text:'Invólucro atravessa H'},{id:'open',text:'Gaveta aberta'},{id:'program',text:'Alerta agendado'},{id:'g',text:'Invólucro chega a G'},{id:'start',text:'Transporte sai de A'},{id:'c',text:'Invólucro chega a C'}],answer:'program,open,start,c,filter,g,gate,alarm',hints:['O agendamento antecede a abertura da gaveta. A saída de A é o ponto de partida para somar os tempos.','Comparem a chegada calculada a H com a abertura dos pulsos. O alerta só acontece dois minutos depois dessa janela.'],explanation:'21h56 agendamento; 22h03 gaveta; 22h05 A; 22h09 C; 22h12 E; 22h15 G; 22h17 H; 22h19 alerta.'},
code('substitution','12 · Duas análises verdadeiras, uma fraude','empathy',['original','contract','identity','residue','sequence'],'O relatório falso usou o resultado de qual amostra NO LUGAR de qual outra? Respondam no formato amostra usada,amostra exigida. A ordem é essencial.','72,27',['Um resultado laboratorial pode estar correto e ainda ser usado para mentir. Comparem a exigência do contrato com a origem da coleta.','Primeiro escrevam o número da amostra limpa que entrou nas páginas substitutas. Depois, o da amostra da obra que o contrato realmente exigia.'],'A amostra 72, limpa e sem relação com a obra, foi usada no lugar da 27, coletada a montante e reprovada. A fraude foi de identidade da amostra, não de cálculo laboratorial.','Número,Número')
],deductions:[
{id:'route-time',a:'route',b:'gate',relation:'explica',text:'Os 12 minutos do trajeto a partir das 22h05 explicam a passagem na única janela de H, às 22h17.'},
{id:'fake-emergency',a:'alarm',b:'sequence',relation:'contradiz',text:'A retirada anterior e o sensor seco contradizem a hipótese de remoção urgente causada por um vazamento real.'},
{id:'custody',a:'residue',b:'loans',relation:'explica',text:'A marca exclusiva de L4 no selante fresco liga o manuseio do laudo retirado à ferramenta sob custódia de Olga.'},
{id:'sample',a:'original',b:'contract',relation:'contradiz',text:'O laudo original reprova a amostra contratualmente exigida e contradiz o aceite que autorizaria a parcela.'},
{id:'innocents',a:'identity',b:'loans',relation:'explica',text:'A escala associada às filmagens contínuas explica a exclusão dos outros três suspeitos na janela da retirada.'},
{id:'genuine',a:'original',b:'manifest',relation:'explica',text:'O lote verificado e os sinais físicos explicam por que as páginas recuperadas pertencem à amostra original, apesar do envelope substituto lacrado.'}
],solution:{suspect:'olga',motive:'Liberar a parcela da obra substituindo a amostra reprovada',motives:['Liberar a parcela da obra substituindo a amostra reprovada','Evitar que Maia descartasse o papel por umidade','Ocultar uma calibração legítima realizada por Nilo','Ajudar Teo a conseguir transferência da estação'],proof:'residue',ending:'Olga retirou o laudo da amostra 27 e colocou no envelope as páginas verdadeiras, mas irrelevantes, da amostra 72. O contrato passaria a parecer cumprido. A marca de L4 no selante fresco do original, somada à custódia filmada e à sua presença na gaveta, liga a troca a ela. As filmagens contínuas excluem os demais.\n\nÀs 22h05 o laudo saiu por A. O percurso de conservação o levou à galeria oito exatamente na abertura de 22h17. O aviso das 22h19, programado antes, criaria uma explicação conveniente para qualquer movimentação percebida depois. A senha compartilhada e o envelope lacrado eram pistas insuficientes, não provas contra uma pessoa específica.\n\nA equipe recupera o original, cancela o aceite e encaminha a obra para nova inspeção. Vocês fecharam o caso combinando autenticidade, oportunidade, custódia, percurso e motivo — nenhum desses elementos resolveria tudo sozinho.'}});
})();
