globalThis.installActThree=(STORY,MAP)=>{
MAP.push({id:'loc_norte',nome:'Passo das Lanternas',icon:'🏔️',desc:'Uma trilha de neve entre a costa e a torre.'},{id:'loc_torrenorte',nome:'Torre das Promessas',icon:'🏰',desc:'O último abrigo da terceira relíquia.'});
delete STORY.fim_ato2.type;
STORY.fim_ato2.text=STORY.fim_ato2.text.replace('O Ato III chega quando vocês pedirem. Até lá, essa é a aventura de vocês dois.','Oriel espera na estrada do norte. A última etapa pode começar quando vocês estiverem prontos.');
STORY.fim_ato2.choices=[{label:'Começar o Ato III — A Torre das Promessas',next:'norte_inicio'}];
const n=(tag,text,choices,extra={})=>({loc:'loc_norte',tag:'Ato III · '+tag,text,choices,...extra});
const c=(label,next)=>({label,next});
Object.assign(STORY,{
norte_inicio:n('A última subida','Oriel segura duas canecas junto a uma fogueira. Uma delas já está fria. “Achei que chegariam ontem.” Karol pega a quente antes de Yudi perceber.\n\nAo norte, uma torre aparece entre as nuvens. As duas relíquias vibram na mesma direção. Oriel oferece abrigo e poções antes da subida.',[c('Perguntar o que existe na torre','norte_oriel'),c('Conferir a trilha','norte_trilha')],{onEnter:st=>{for(const k of ['yudi','karol']){st[k].hp=st[k].maxHp;st[k].inventory.push('Poção de Cura')}}}),
norte_oriel:n('O que Oriel não contou','“O guardião não perdeu a memória”, Oriel diz. “Ele se lembra de todas as pessoas que prometeram voltar e não voltaram. O Véu se alimenta disso. Vocês podem vencê-lo, mas talvez consigam fazê-lo escutar.”\n\nEla entrega uma corda com três nós. “E não tentem atravessar a ponte abraçados. Uma pessoa por vez.”',[c('Guardar a corda e seguir','norte_trilha')],{onEnter:st=>{st.flags.northRope=true;st.yudi.inventory.push('Corda de Oriel');st.karol.inventory.push('Corda de Oriel')}}),
norte_trilha:n('Duas maneiras de subir','A trilha curta passa por uma ponte suspensa. A longa contorna um bosque de pinheiros. Pegadas de lobo desaparecem entre os troncos. Na ponte, a última tábua balança sozinha.',[c('Atravessar a ponte com cuidado','norte_ponte'),c('Contornar pelo bosque','norte_lobos')]),
norte_ponte:n('Um passo de cada vez','Uma pessoa prende a corda, a outra testa as tábuas. Quem vai conduzir a travessia?',[],{type:'check',check:{stat:'destreza',dc:13,label:'Atravessar a ponte',itemBonus:{item:'Corda de Oriel',value:3},success:'norte_ponte_ok',fail:'norte_ponte_falha'}}),
norte_ponte_ok:n('Do outro lado','A madeira estala, mas vocês chegam com as mochilas secas. Yudi olha para trás. “A volta vai ser por outro caminho.”',[c('Procurar abrigo','norte_abrigo')]),
norte_ponte_falha:n('Neve dentro da bota','Uma tábua cede. A queda termina numa encosta de neve, poucos metros abaixo. Vocês saem arranhados e encontram uma escada de manutenção. Perdem 4 de vida cada, mas a subida continua.',[c('Subir pela escada','norte_abrigo')],{onEnter:st=>{for(const k of ['yudi','karol'])st[k].hp=Math.max(1,st[k].hp-4)}}),
norte_lobos:n('O bosque sem pássaros','Os lobos do Véu cercam a trilha. As marcas violetas se apagam por instantes quando as relíquias se aproximam. Abram caminho sem se separar.',[],{type:'combat',combat:{enemyName:'Lobos do Véu',enemyHp:30,enemyAtkMin:3,enemyAtkMax:7,enemyDef:12,enemyAcc:5,win:'norte_abrigo'}}),
norte_abrigo:n('A casa sob os pinheiros','Vovó Sarça abre a porta antes de vocês baterem. “Vocês fazem barulho demais para duas pessoas com frio.” Há sopa, um cobertor e um caderno sobre a mesa. Aqui vocês recuperam a vida.\n\nNa capa: MANUTENÇÃO DAS LANTERNAS. Alguém deixou uma anotação sobre o guardião no verso.',[c('Ler o caderno das lanternas','norte_caderno'),c('Perguntar sobre o guardião','norte_sarca')],{onEnter:st=>{for(const k of ['yudi','karol'])st[k].hp=st[k].maxHp}}),
norte_sarca:n('Uma promessa incompleta','“Ele pediu a Oriel que protegesse a torre”, Sarça conta. “Ela saiu para buscar ajuda e ele achou que tinha sido abandonado.”\n\nSarça entrega uma carta antiga. Nela, Oriel prometia VOLTAR, não ficar. A carta jamais chegou à torre.',[c('Guardar a carta e ler o caderno','norte_caderno')],{onEnter:st=>{st.flags.northLetter=true;st.yudi.inventory.push('Carta não entregue')}}),
norte_caderno:n('O caderno das lanternas','Quatro lanternas, da esquerda para a direita. Cada uma mostra um algarismo. A segunda vale o dobro da primeira. A terceira vale a segunda menos um. A quarta vale a soma da primeira e da terceira. A soma das quatro é 22. Todas usam algarismos de 1 a 9.\n\nKarol copia a regra na palma da mão. A porta da torre usa a sequência inteira.',[c('Ir até a porta da torre','norte_porta')]),
norte_porta:n('Quatro luzes','A inscrição repete: segunda = 2 × primeira; terceira = segunda − 1; quarta = primeira + terceira; soma = 22. Que sequência acende a porta?',[],{loc:'loc_torrenorte',type:'riddle',riddle:{answer:'3658',next:'norte_sala',hint:'Somando em função da primeira lanterna x: 8x−2=22. Descubram x e calculem as outras três.',prompt:'Os quatro algarismos'}}),
norte_sala:n('Uma voz de pedra','O Golem de Pedra está de pé junto ao altar. É o mesmo guardião da primeira relíquia: veio atrás de vocês pelas galerias antigas. Agora o Véu toma suas juntas.\n\n“Ela disse que voltava.” Ele repete isso olhando para a porta, não para vocês.',[c('Procurar a carta na mochila','norte_carta'),c('Examinar o altar antes de responder','norte_altar'),c('Enfrentar o guardião','norte_combate')],{loc:'loc_torrenorte'}),
norte_carta:n('O envelope','A carta de Oriel pode mudar esta conversa, se vocês a trouxeram.',[c('Apresentar o que encontramos','norte_carta_resultado')],{loc:'loc_torrenorte'}),
norte_carta_resultado:n('Uma resposta atrasada','',[],{loc:'loc_torrenorte',branch:st=>st.flags.northLetter?'norte_paz':'norte_semcarta'}),
norte_semcarta:n('A mochila vazia','A carta ficou com Sarça. Vocês podem voltar para buscá-la. O guardião não vai acreditar apenas na palavra de dois desconhecidos.',[c('Voltar ao abrigo e ouvir Sarça','norte_sarca'),c('Voltar ao altar','norte_altar')],{loc:'loc_torrenorte'}),
norte_paz:n('A letra que ele reconheceu','O guardião segura o envelope entre dois dedos enormes. “Ela escreveu meu nome.” Pela primeira vez, sua voz deixa de ecoar como uma ordem.\n\nAs manchas violetas recuam. Ele permite que vocês alcancem o altar sem combate.',[c('Examinar as três posições do altar','norte_altar')],{loc:'loc_torrenorte',onEnter:st=>{st.flags.northPeace=true}}),
norte_combate:n('Pedra contra o Véu','O guardião avança. As relíquias protegem vocês do frio, mas não dos golpes. A luta termina quando a crosta do Véu se rompe.',[],{loc:'loc_torrenorte',type:'combat',combat:{enemyName:'Golem de Pedra',enemyHp:54,enemyAtkMin:4,enemyAtkMax:8,enemyDef:13,enemyAcc:6,win:'norte_vitoria'}}),
norte_vitoria:n('O que sobra da sombra','O golem cai de joelhos, inteiro sob a crosta que se partiu. “Ainda dá tempo?”, pergunta. Vocês apontam para a porta aberta.',[c('Completar o altar','norte_altar')],{loc:'loc_torrenorte',onEnter:st=>{st.flags.northVictory=true}}),
norte_altar:n('Três lugares à mesa','No altar há três encaixes: COMEÇO, CAMINHO e CHEGADA. Uma inscrição: “A pedra sustenta o primeiro passo. A água atravessa o caminho. A luz encontra o que falta.”\n\nEscrevam os três elementos na ordem dos encaixes, separados por vírgulas.',[],{loc:'loc_torrenorte',type:'riddle',riddle:{answer:'pedra,agua,luz',next:'norte_ritual',prompt:'Elemento,elemento,elemento',hint:'Leiam a função de cada elemento: primeiro passo, caminho e encontro.'}}),
norte_ritual:n('Ainda falta uma escolha','',[],{loc:'loc_torrenorte',branch:st=>st.flags.northPeace||st.flags.northVictory?'norte_reliquia':'norte_bloqueio'}),
norte_bloqueio:n('A mão sobre o altar','O guardião cobre a relíquia com a mão. Decifrar o altar não resolveu a desconfiança dele. Vocês precisam entregar a carta ou romper o Véu em combate.',[c('Conversar sobre a carta','norte_carta'),c('Enfrentar o guardião','norte_combate')],{loc:'loc_torrenorte'}),
norte_reliquia:n('O Coração de Luz','O terceiro fragmento cabe entre os outros dois. Oriel chega à porta sem fôlego. O guardião não diz nada; apenas afasta a mão e deixa Oriel entrar.\n\nEnquanto ela inicia o contra-ritual, Yudi e Karol seguram as relíquias. O frio não some de uma vez. Primeiro, vocês voltam a ouvir o vento. Depois, um pássaro.',[c('Descer juntos ao amanhecer','norte_final')],{loc:'loc_torrenorte',onEnter:st=>{st.flags.relic3=true;for(const k of ['yudi','karol']){st[k].maxHp+=4;st[k].hp=st[k].maxHp;st[k].inventory.push('Fragmento do Coração de Luz')}}}),
norte_final:n('Fim do Ato III','Na descida, Karol encontra o desenho das lanternas ainda na mão. Está quase apagado. Yudi oferece a própria manga e ela ri.\n\nTrês relíquias. Uma torre aberta. E uma viagem de volta que, pela primeira vez, não precisa ser feita com pressa. Vocês ganharam 4 pontos de vida máxima cada e guardaram um fragmento da luz.\n\nO capítulo está concluído e salvo. Podem voltar ao site sem recomeçar a campanha.',[],{type:'end'})
});
};
